name: calligro_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.9.2"  # Supports Dart 2.12 and higher (null safety)

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.2.1
  exif: ^3.3.0

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.3
  cloud_functions: ^6.0.4
  firebase_app_check: ^0.4.1+2

  # 🌐 LATEST STABLE UTILITIES
  google_sign_in: ^7.0.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  url_launcher: ^6.2.6
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  flutter_appauth: ^10.0.0
  intl: ^0.20.2
  in_app_purchase: ^3.2.0  # ✅ REQUIRED for App Store/Play Store digital goods
  jitsi_meet_flutter_sdk: ^11.6.0
  crypto: ^3.0.3
  
  # OTHER PACKAGES
  phone_number: ^2.0.1
  country_code_picker: ^3.0.0
  intl_phone_field: 3.0.1
  flutter_dotenv: ^6.0.0
  #flutter_haptic_feedback: ^1.0.1
  device_region: ^1.1.0
  timezone: ^0.10.1
  geolocator: ^14.0.2
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.0
  firebase_storage: ^13.0.3
  timeago: ^3.7.1
  audioplayers: ^6.5.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.0.15
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  sqflite: ^2.3.0 
  shimmer: ^3.0.0
  video_player: ^2.7.0
  flutter_animate: ^4.5.2
  share_plus: ^12.0.1
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.3.8
  translator: ^1.0.4+1
  rxdart: ^0.28.0
  app_links: ^6.4.1
  lottie: ^3.3.2
  flutter_local_notifications: ^20.1.0
  flutter_native_splash: ^2.3.1
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  wechat_assets_picker: ^10.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ✅ App Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/artists/
    - assets/backgrounds/
    - assets/courses_backgrounds/
    - assets/videos/
    - assets/videos/numbers.m4v
    - assets/icons/
    - .env
    - assets/client_secret.json

# ✅ App Icon Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_zoomed.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1F1F1F" 
  adaptive_icon_foreground: "assets/images/Logo_zoomed.png"
  # ✅ Fix iOS White Border (Opaque Image Used)
  remove_alpha_ios: true
  background_color_ios: "#1F1F1F"

# ✅ ADDED: Native Splash Screen Configuration
flutter_native_splash:
  color: "#1F1F1F" # Background matches your theme
  image: "assets/images/splash_blank.png" # ✅ ADDED: Blank image to hide default icon
  fullscreen : true
  android_12:
    color: "#1F1F1F"
    icon_background_color: "#1F1F1F"
