import 'package:flutter/material.dart';
import 'package:calligro_app/l10n/app_localizations.dart';

class CourseUtils {
  static String getLocalizedCourseName(BuildContext context, Map<String, dynamic> data) {
    final l10n = AppLocalizations.of(context)!;
    
    // If it's a manual name, return it as is
    final bool isAutoGenerated = data['isAutoGeneratedName'] ?? true;
    final String savedName = (data['courseName']?.toString() ?? '').trim();
    
    // If we have a manual name that isn't white-space, use it UNLESS we are explicitly told it's auto-generated
    if (!isAutoGenerated && savedName.isNotEmpty && savedName != 'Untitled') {
      return savedName;
    }

    // Try to regenerate from writingType/calligraphyStyle
    final writingType = data['writingType'] as String?;
    final calligraphyStyle = data['calligraphyStyle'] as String?;
    final category = data['selectedCategory'] as String?;

    if (writingType != null && category != null) {
      String subject = "";
      
      if (writingType == "Normal Pen Writing") {
        subject = l10n.normalPenWriting;
      } else {
        String styleKey = calligraphyStyle ?? "Calligraphy";
        switch (styleKey) {
          case "Kufi": subject = l10n.kufi; break;
          case "Naskh": subject = l10n.naskh; break;
          case "Ruq'ah": subject = l10n.ruqah; break;
          case "Thuluth": subject = l10n.thuluth; break;
          case "Jali Thuluth": subject = l10n.jaliThuluth; break;
          case "Diwani": subject = l10n.diwani; break;
          case "Jali Diwani": subject = l10n.jaliDiwani; break;
          case "Persian (Ta'liq)": subject = l10n.persianTaliq; break;
          case "Ijaza": subject = l10n.ijaza; break;
          case "Muhaqqaq": subject = l10n.muhaqqaq; break;
          case "Rayhani": subject = l10n.rayhani; break;
          default: subject = l10n.arabicCalligraphy; break;
        }
      }

      String level = getLocalizedLevel(context, category);
      return l10n.courseNameTemplate(subject, level);
    }

    return savedName;
  }

  static String getLocalizedLevel(BuildContext context, String? level) {
    if (level == null) return "";
    final l10n = AppLocalizations.of(context)!;
    
    switch (level) {
      case 'Beginner':
        return l10n.beginner;
      case 'Intermediate':
        return l10n.intermediate;
      case 'Advanced':
        return l10n.advanced;
      default:
        return level;
    }
  }

  static String getLocalizedAge(BuildContext context, String? age) {
    if (age == null || age.isEmpty) return "";
    final locale = Localizations.localeOf(context).languageCode;
    
    if (age == '7-10') {
      if (locale == 'ar') return '7-10 سنوات';
      if (locale == 'tr') return '7-10 Yaş';
      return '7-10 Years';
    } else if (age == '11-16') {
      if (locale == 'ar') return '11-16 سنة';
      if (locale == 'tr') return '11-16 Yaş';
      return '11-16 Years';
    } else if (age == '17+') {
      if (locale == 'ar') return '17+ سنة';
      if (locale == 'tr') return '17+ Yaş';
      return '17+ Years Old';
    }
    return age;
  }

  static bool isAutoGenerated(String name, AppLocalizations l10n) {
    // This is a fuzzy check if we don't have the flag yet.
    // For now, we'll rely on the flag 'isAutoGeneratedName'.
    return false; 
  }

  /// Normalizes Arabic/Indic digits to standard English digits (0-9).
  static String normalizeNumerics(String input) {
    if (input.isEmpty) return "";
    const Map<String, String> digitMap = {
      '٠': '0', '١': '1', '٢': '2', '٣': '3', '٤': '4',
      '٥': '5', '٦': '6', '٧': '7', '٨': '8', '٩': '9',
      '۰': '0', '۱': '1', '۲': '2', '۳': '3', '۴': '4',
      '۵': '5', '۶': '6', '۷': '7', '۸': '8', '۹': '9',
    };

    String result = input;
    digitMap.forEach((key, value) {
      result = result.replaceAll(key, value);
    });
    return result;
  }

  /// Normalizes Arabic text for searching:
  /// - Standardizes Alif (أ, إ, آ -> ا)
  /// - Standardizes Taa Marbuta (ة -> ه)
  /// - Standardizes Ya (ى -> ي)
  /// - Removes Arabic diacritics (Harakat)
  static String normalizeArabic(String text) {
    if (text.isEmpty) return "";
    
    String normalized = text;

    // Remove Harakat (Diacritics)
    final harakatRegex = RegExp(r"[\u064B-\u0652]");
    normalized = normalized.replaceAll(harakatRegex, "");

    // Normalize Alif
    normalized = normalized.replaceAll(RegExp(r"[أإآ]"), "ا");

    // Normalize Taa Marbuta to Haa (Common in search)
    normalized = normalized.replaceAll("ة", "ه");

    // Normalize Ya
    normalized = normalized.replaceAll("ى", "ي");

    return normalized;
  }

  /// Combined normalization for English and Arabic search
  static String prepareForSearch(String text) {
    String res = text.toLowerCase().trim();
    res = normalizeNumerics(res);
    res = normalizeArabic(res);
    return res;
  }
}
