// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgj1z12glctRJ-LjD8ebyZLDfFf_EDhwM',
    appId: '1:500166558232:web:88e9a2f3556a3a3361396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    authDomain: 'calligro-bcfb2.firebaseapp.com',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
    measurementId: 'G-0507DP0E4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebAi7veB2DgOiVcPiEgGRpgtkJidBUsc',
    appId: '1:500166558232:android:c4006edb06d928fe61396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ErEEVSf1ATwGEUoF--wYGJgbzKz43vU',
    appId: '1:500166558232:ios:35b6158b88b3a4a061396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
    androidClientId: '500166558232-gvffubev0gu5no6i5pf1hq4sa4pkqvdh.apps.googleusercontent.com',
    iosClientId: '500166558232-aoh4tfkis9714nsqh2ugilougns1q27q.apps.googleusercontent.com',
    iosBundleId: 'com.yazan.calligroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ErEEVSf1ATwGEUoF--wYGJgbzKz43vU',
    appId: '1:500166558232:ios:35b6158b88b3a4a061396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
    androidClientId: '500166558232-gvffubev0gu5no6i5pf1hq4sa4pkqvdh.apps.googleusercontent.com',
    iosClientId: '500166558232-aoh4tfkis9714nsqh2ugilougns1q27q.apps.googleusercontent.com',
    iosBundleId: 'com.yazan.calligroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgj1z12glctRJ-LjD8ebyZLDfFf_EDhwM',
    appId: '1:500166558232:web:d52aef4ad576015761396d',
    messagingSenderId: '500166558232',
    projectId: 'calligro-bcfb2',
    authDomain: 'calligro-bcfb2.firebaseapp.com',
    storageBucket: 'calligro-bcfb2.firebasestorage.app',
    measurementId: 'G-WZD4M3VMDW',
  );

}