services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    network_mode: "host"

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    depends_on:
      - redis

  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - SYS_ADMIN
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress/config.yaml
    volumes:
      - ./config.yaml:/etc/egress/config.yaml:ro
      - /tmp/egress_backup:/tmp/egress_backup
    depends_on:
      - redis
      - livekit
